---
name: Run nox sessions

on:
  pull_request:
    branches:
      - main
    ## Do not trigger tests when only these files have changed
    paths-ignore:
      - "README.md"
      - "noxfile.py"
      - ".gitignore"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  run-nox-sessions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ github.token }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Setup nox action
        uses: fjwillemsen/setup-nox2@v3.0.0

      - name: "Run nox sessions"
        run: nox
